name: gab_ai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  country_code_picker: ^3.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  image_picker: ^1.1.2
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/BG.png
    - assets/logo-word.png
    - assets/facebook.png
    - assets/google.png
    - assets/email_sent.png
    - assets/preg_icon.png
    - assets/nd_icon.png
    - assets/otp.png
    - assets/word-only.png

  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Regular.ttf
        - asset: assets/fonts/Merriweather-Bold.ttf
          weight: 700
        - asset: assets/fonts/Merriweather-Italic.ttf
          style: italic
        - asset: assets/fonts/Merriweather-BoldItalic.ttf
          style: italic

    - family: Nunito Sans
      fonts:
        - asset: assets/fonts/NunitoSans-Italic.ttf
          style: italic
        - asset: assets/fonts/NunitoSans-Regular.ttf