name: gab_ai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  carousel_slider: ^5.0.0
  country_code_picker: ^3.0.0
  file_picker: ^8.1.2
  fluentui_system_icons: ^1.1.255
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^7.0.1
  flutter_launcher_icons: ^0.13.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  pin_code_fields: ^8.0.1
  stylish_bottom_bar: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#FFF5E1"
  adaptive_icon_foreground: "assets/icons/fg.png"

flutter:
  uses-material-design: true
  assets:
    - assets/BG.png
    - assets/logo-word.png
    - assets/facebook.png
    - assets/google.png
    - assets/email_sent.png
    - assets/preg_icon.png
    - assets/nd_icon.png
    - assets/otp.png
    - assets/check.png
    - assets/check_small.png
    - assets/ok.png
    - assets/profiles/default-boy.png
    - assets/profiles/default-girl.png
    - assets/default.png
    - assets/icons/icon_appointments.png
    - assets/icons/icon_mealplan.png
    - assets/icons/icon_journal.png
    - assets/icons/icon_breakfast.png
    - assets/icons/icon_breakfast_outlined.png
    - assets/icons/icon_lunch_outlined.png
    - assets/icons/icon_snacks_outlined.png
    - assets/icons/icon_dinner_outlined.png
    - assets/icons/fg.png
    - assets/background_images/
    - assets/cover_photos/
    - assets/icons/icon_message.png
    - assets/icons/icon_message-2.png

  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Regular.ttf
        - asset: assets/fonts/Merriweather-Bold.ttf
          weight: 700
        - asset: assets/fonts/Merriweather-Italic.ttf
          style: italic
        - asset: assets/fonts/Merriweather-BoldItalic.ttf
          style: italic

    - family: Nunito Sans
      fonts:
        - asset: assets/fonts/NunitoSans-Italic.ttf
          style: italic
        - asset: assets/fonts/NunitoSans-Regular.ttf